# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных.

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией.
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

 С этими библиотеками вы будете знакомится дальше на курсе, а пока давайте попрактикуемся в решении базовых задач на  чистом Python.

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [ ]:
def share_bread(N, K):
    x = K/N
    y = (x - int(x)) * N
    return int(x), round(y)  

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=23) == (7, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [30]:
import calendar
def leap_year(year):
    if calendar.isleap(year):
        return "YOU SHALL PASS"
    return "YOU SHALL NOT PASS"

assert leap_year(1900) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>


Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

**Подсказка:** используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [5]:
import math
def amulet_area(a, b, c):
    p = (a+b+c)/2
    S = math.sqrt(p*(p-a)*(p-b)*(p-c))
    return S

assert amulet_area(3, 4, 5) == 6


## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - написать функцию под каждую из них. Важное условие - используйте только базовые функции для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [9]:
%pip install numpy
def cal_euclidean(a, b):
    sum_of_squares = 0
    
    # Проходим по всем индексам координат
    for a_i, b_i in zip(a, b):
        # Находим разницу по координате
        diff = a_i - b_i
        # Возводим разницу в квадрат и добавляем к сумме
        sum_of_squares += diff * diff  # то же самое, что (diff) ** 2
    
    # Возводим сумму в степень 0.5 (эквивалент взятию корня)
    distance = sum_of_squares ** 0.5
    return distance

def cal_manhattan(a, b):
    distance = 0
    
    for a_i, b_i in zip(a, b):
        distance += abs(a_i - b_i)
    return distance

def cal_cosine(a, b):
    def dot_product(vec1, vec2):
        return sum(x * y for x, y in zip(vec1, vec2))

    def norm(vec):
        return sum(x ** 2 for x in vec) ** 0.5
    
    dp = dot_product(a, b)
    norm_a = norm(a)
    norm_b = norm(b)

    cosine_similarity = dp / (norm_a * norm_b)
    distance = 1 - cosine_similarity

    return distance

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 4.3 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 25.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

22.516660498395403
57
0.8586021940832653


## Задача 5* (бонусное неоцениваемое задание)

**Замечание:** Поскольку библиотеку numpy мы будем подробно разбирать дальше, то это задание является бонусным, его выполнение необязательно для сдачи ДЗ и не влияет на итоговый балл. Как вариант, можете вернуться к нему после прохождения numpy ;)



Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в интервале от 0 до 1 остаются прежними

In [22]:
my_array = np.random.rand(100)
print(np.max(my_array), np.min(my_array))
print(my_array)

0.9995429026754693 0.029787324876009214
[0.58078184 0.48332376 0.72447501 0.79568585 0.58143115 0.30419598
 0.73751947 0.93487164 0.34786543 0.33132339 0.43916767 0.84034411
 0.24529924 0.64355823 0.45027384 0.9995429  0.80200959 0.69403038
 0.17178307 0.2173341  0.72065728 0.22793738 0.0888774  0.68049952
 0.56670366 0.4770241  0.49470766 0.89584135 0.63904304 0.58498037
 0.84101127 0.95223947 0.70431754 0.42460293 0.23099529 0.71671687
 0.95843715 0.1630719  0.45355517 0.40429936 0.95021523 0.86453487
 0.37854038 0.50679743 0.15993275 0.5454927  0.50958631 0.0372615
 0.03463683 0.25705463 0.72186551 0.12512391 0.22754    0.96256012
 0.16276208 0.86198124 0.26911659 0.53962431 0.31551985 0.14747334
 0.34576163 0.78907381 0.83803884 0.80734821 0.73614132 0.02978732
 0.49496529 0.31673838 0.7627975  0.1644493  0.61581053 0.16604492
 0.40784476 0.8830158  0.83216153 0.37828881 0.66707452 0.51665672
 0.71386036 0.32024832 0.39856489 0.68159965 0.55462108 0.69344657
 0.2760804  0.8885733  

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы

In [25]:
my_array = np.random.randint(0, 50, size=(5,6))
selected_column = np.max(my_array)
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Shape:  (5, 6)
Array
[[17 14 21  7 38 48]
 [41 27 35 49  9 31]
 [14 47  8 10 35  1]
 [49 45 45  0 20 25]
 [ 1 19 18 18 14 28]]
49


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [ ]:
def get_unique_rows(X):
    x = [tuple(x) for x in X]
    y = set(x)
    X_unique = np.array([list(i) for i in y])
    return X_unique

In [73]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[4 5 4]
 [5 4 5]
 [5 4 5]
 [4 5 4]
 [4 5 5]
 [5 5 4]
 [4 4 4]
 [5 4 4]
 [5 5 4]
 [4 5 5]]


In [74]:
get_unique_rows(X)

{(np.int64(4), np.int64(4), np.int64(4)),
 (np.int64(4), np.int64(5), np.int64(4)),
 (np.int64(4), np.int64(5), np.int64(5)),
 (np.int64(5), np.int64(4), np.int64(4)),
 (np.int64(5), np.int64(4), np.int64(5)),
 (np.int64(5), np.int64(5), np.int64(4))}